### ISSUE TITLE
Version bump & irssi/scripts.irssi.org#145

### ISSUE THREAD

**Issue by GeertHauwaerts** [mjholtkamp/irssi-trackbar#7]
Can you update your version 1.8 to 1.9 with the irssi/scripts.irssi.org#145 fix included?

I will merge your 1.9 into the scripts.irssi.org repository afterwards.

**Comment by bw1** [comment]
thanks for contact us

the problem with this bug is

we can not reproduce this bug

on my home system is irssi 0.8.15 (20100403 1617)
and this give no trouble

in the test system on the rpi is
working a irssi 0.8.15 (20100403 1617)
also no problem

**Comment by mjholtkamp** [comment]
Hi @GeertHauwaerts, sure I can add it, but it might block people from using this script with older versions (as  @bw1) mentioned. @bw1: I'm curious, is there a reason why you are not using a more recent version?

**Comment by ailin-nemui** [comment]
a bug in older irssi with regard to adding lines is triggered frequently by your version of `trackbar`.

If you resize older irssi franatically with trackbar visible and have incoming channel messages, you may end up in a situation where `--MORE--` appears but it is impossible to scroll down to actually read those messages. While it is actually a bug in irssi, this trackbar triggers it quite easily and there were many cases of this issue in freenode'`#irssi`. People do get their scripts from `scripts.irssi.org`, that's why this is especially troublesome to have your version of trackbar present there IMHO

Also see issue #6

**Comment by GeertHauwaerts** [comment]
I am in favor of pathcing the script with the version bump; there is no reason we should not update script just because of incompatibility with older versions of Irssi.
